#This file is generated by seedit-converter
######Begin of normal files/dirs
/(|.*)	 gen_context(system_u:object_r:default_t,s0)
/(|[^/]*) 	 gen_context(system_u:object_r:rootdir_t,s0)
/[^/]+/.+ 	 gen_context(system_u:object_r:childdir__t,s0)
/[^/]+ -d  gen_context(system_u:object_r:dir_childdir__t,s0)
/bin(|/.*)	gen_context(system_u:object_r:bin_t,s0)
/dev(|/.*)	gen_context(system_u:object_r:dev_t,s0)
/etc(|/.*)	gen_context(system_u:object_r:etc_t,s0)
/etc/cron.d(|/.*)	gen_context(system_u:object_r:system_cron_spool_t,s0)
/etc/rc.d(|/.*)	gen_context(system_u:object_r:etc_rcdd_t,s0)
/etc/selinux(|/.*)	gen_context(system_u:object_r:etc_selinux_t,s0)
/lib(|/.*)	gen_context(system_u:object_r:lib_t,s0)
/sbin(|/.*)	gen_context(system_u:object_r:sbin_t,s0)
/tmp(|/.*)	gen_context(system_u:object_r:tmp_t,s0)
/usr(|/.*)	gen_context(system_u:object_r:usr_t,s0)
/usr/lib(|/.*)	gen_context(system_u:object_r:usr_lib_t,s0)
/usr/share(|/.*)	gen_context(system_u:object_r:usr_share_t,s0)
/usr/share/locale(|/.*)	gen_context(system_u:object_r:usr_share_locale_t,s0)
/usr/share/zoneinfo(|/.*)	gen_context(system_u:object_r:usr_share_zoneinfo_t,s0)
/var(|/.*)	gen_context(system_u:object_r:var_t,s0)
/var/log(|/[^/]*) 	 gen_context(system_u:object_r:var_log_t,s0)
/var/log/[^/]*/.+ 	 gen_context(system_u:object_r:var_log__childdir__t,s0)
/var/log/[^/]* -d  gen_context(system_u:object_r:dir_var_log__childdir__t,s0)
/var/run(|/.*)	gen_context(system_u:object_r:var_run_t,s0)
/var/run/nscd(|/.*)	gen_context(system_u:object_r:var_run_nscd_t,s0)
/var/spool/cron(|/.*)	gen_context(system_u:object_r:system_cron_spool_t,s0)
/var/tmp(|/.*)	gen_context(system_u:object_r:var_tmp_t,s0)
#Normal files
/sbin/syslogd	gen_context(system_u:object_r:sbin_syslogd_t,s0)
/sbin/minilogd	gen_context(system_u:object_r:sbin_minilogd_t,s0)
/sbin/ldconfig	gen_context(system_u:object_r:sbin_ldconfig_t,s0)
/sbin/init	gen_context(system_u:object_r:sbin_init_t,s0)
/etc/syslog.conf	gen_context(system_u:object_r:etc_syslogdconf_t,s0)
/etc/shadow-	gen_context(system_u:object_r:etc_shadowm_t,s0)
/etc/shadow	gen_context(system_u:object_r:etc_shadow_t,s0)
/etc/services	gen_context(system_u:object_r:etc_services_t,s0)
/etc/selinux/config	gen_context(system_u:object_r:etc_selinux_config_t,s0)
/etc/resolv.conf	gen_context(system_u:object_r:etc_resolvdconf_t,s0)
/etc/rc.d/rc.sysinit	gen_context(system_u:object_r:etc_rcdd_rcdsysinit_t,s0)
/etc/rc.d/rc.local	gen_context(system_u:object_r:etc_rcdd_rcdlocal_t,s0)
/etc/rc.d/rc	gen_context(system_u:object_r:etc_rcdd_rc_t,s0)
/etc/rc.d/init.d	gen_context(system_u:object_r:etc_rcdd_initdd_t,s0)
/etc/protocols	gen_context(system_u:object_r:etc_protocols_t,s0)
/etc/passwd	gen_context(system_u:object_r:etc_passwd_t,s0)
/etc/nsswitch.conf	gen_context(system_u:object_r:etc_nsswitchdconf_t,s0)
/etc/localtime	gen_context(system_u:object_r:etc_localtime_t,s0)
/etc/init.d	gen_context(system_u:object_r:etc_initdd_t,s0)
/etc/hosts.deny	gen_context(system_u:object_r:etc_hostsddeny_t,s0)
/etc/hosts.allow	gen_context(system_u:object_r:etc_hostsdallow_t,s0)
/etc/hosts	gen_context(system_u:object_r:etc_hosts_t,s0)
/etc/host.conf	gen_context(system_u:object_r:etc_hostdconf_t,s0)
/etc/group	gen_context(system_u:object_r:etc_group_t,s0)
/etc/environment	gen_context(system_u:object_r:etc_environment_t,s0)
/etc/crontab	gen_context(system_u:object_r:system_cron_spool_t,s0)
/dev/zero	gen_context(system_u:object_r:dev_zero_t,s0)
/dev/urandom	gen_context(system_u:object_r:dev_urandom_t,s0)
/dev/random	gen_context(system_u:object_r:dev_random_t,s0)
/dev/port	gen_context(system_u:object_r:dev_port_t,s0)
/dev/null	gen_context(system_u:object_r:null_device_t,s0)
/dev/mem	gen_context(system_u:object_r:dev_mem_t,s0)
/dev/kmem	gen_context(system_u:object_r:dev_kmem_t,s0)
/dev/console	gen_context(system_u:object_r:dev_console_t,s0)
/bin/login	gen_context(system_u:object_r:bin_login_t,s0)
#These labels are to support dir:search permission
/	-d	gen_context(system_u:object_r:dir_rootdir_t,s0)
/lib	-d	gen_context(system_u:object_r:dir_lib_t,s0)
/bin	-d	gen_context(system_u:object_r:dir_bin_t,s0)
/etc	-d	gen_context(system_u:object_r:dir_etc_t,s0)
/dev	-d	gen_context(system_u:object_r:dir_dev_t,s0)
/var	-d	gen_context(system_u:object_r:dir_var_t,s0)
/usr	-d	gen_context(system_u:object_r:dir_usr_t,s0)
/sbin	-d	gen_context(system_u:object_r:dir_sbin_t,s0)
/var/log	-d	gen_context(system_u:object_r:dir_var_log_t,s0)
/usr/lib	-d	gen_context(system_u:object_r:dir_usr_lib_t,s0)
/var/run	-d	gen_context(system_u:object_r:dir_var_run_t,s0)
/etc/rc.d	-d	gen_context(system_u:object_r:dir_etc_rcdd_t,s0)
/usr/share	-d	gen_context(system_u:object_r:dir_usr_share_t,s0)
/etc/selinux	-d	gen_context(system_u:object_r:dir_etc_selinux_t,s0)
/var/run/nscd	-d	gen_context(system_u:object_r:dir_var_run_nscd_t,s0)
/usr/share/locale	-d	gen_context(system_u:object_r:dir_usr_share_locale_t,s0)
/usr/share/zoneinfo	-d	gen_context(system_u:object_r:dir_usr_share_zoneinfo_t,s0)
#End of dir:search
######End of normal files/dirs
##### Home directories
/home/(|.*)	gen_context(system_u:object_r:homedir_rootdir_t,s0)
#These labels are to support dir:search permission
/home	gen_context(system_u:object_r:dir_homedir_rootdir_t,s0)
/home/[^/]+	gen_context(system_u:object_r:dir_homedir_rootdir_t,s0)
#End of dir:search
##### End of Home directories
##### Individual user home
#Normal files
#These labels are to support dir:search permission
#End of dir:search
##### End of individual user home
####Begin of special files
#These labels are to protect Terminal
/dev/[^/]*tty[^/]* 	gen_context(system_u:object_r:tty_device_t,s0)
/dev/[^/]*pty[^/]* 	gen_context(system_u:object_r:tty_device_t,s0)
/dev/pts	gen_context(system_u:object_r:devpts_t)
/dev/pts(/.*)?	<<none>>
/dev/vcs[^/]*	gen_context(system_u:object_r:vcs_device_t,s0)
/dev/tty	gen_context(system_u:object_r:devtty_t,s0)
/dev/ptmx	gen_context(system_u:object_r:ptmx_t,s0)
#Ignore proc
/proc(/.*)?             <<none>>
/var/named/chroot/proc(/.*)?             <<none>>
/sys(/.*)?             <<none>>
/selinux(/.*)?	<<none>>
####End of special files
####Start of dummy files for MCS, modular policy

 ifdef(`enable_mcs', `
 ifdef(`out_dummy', `
HOME_ROOT/dummy -b <<none>>
HOME_DIR/dummy -b  <<none>>
/dummy/dummy-USER -b  gen_context(system_u:object_r:ROLE_dummy_t,s0)
')
')
####End of dummy files
#These files are labeled by file_type_auto_trans
#start of file:dynamic_contexts

/dev/log gen_context(system_u:object_r:dev_log_t,s0)
/etc/fstab      gen_context(system_u:object_r:etc_runtime_t,s0)
/etc/mtab gen_context(system_u:object_r:etc_runtime_t,s0)
/etc/ld.so.cache gen_context(system_u:object_r:ldconfig_cache_t,s0)
#end of file:dynamic_contexts

